test test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,18 @@
-npm test
+
+# Disable commit to main branch
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ]; then
+    echo "You can't commit directly to main branch"
+    exit 1
+fi
+
+
+# Disable commit to branch created locally
+valid_chars="^([0-9]+)-([a-z0-9-]+)$"
+message='Your branch must be created from issue. e.g. 12-branch-name'
+
+if [[ ! $branch =~ $valid_chars ]]; then
+    printf '%s\n' "$message"
+    exit 1
+fi
